log_level: "debug"
listen: ":8080"
enable_server_tls: true
cert: "test/server.crt"
key: "test/server.key"
cf_api: "https://api.cf.sap.hana.ondemand.com"
agent_port: "9494"
client_cert: "test/client.crt"
client_key: "test/client.key"
agent_ca: "test/cacert.pem"
agent_common_name: "pcap-server.service.cf.internal"
agent_tls_skip_verify: "false"
cli_download_root: "cli/build"
